package com.asg.finance.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "GL_ADVANCE_PETTY_CASH_HDR")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AdvancePettyCashHdr {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "TRANSACTION_POID")
    private Long transactionPoid;
    
    @Column(name = "TRANSACTION_DATE", nullable = false)
    private LocalDate transactionDate;
    
    @Column(name = "GROUP_POID")
    private Long groupPoid;
    
    @Column(name = "COMPANY_POID")
    private Long companyPoid;

    // Generated by Trigger
    @Column(name = "DOC_REF", nullable = false, length = 100)
    private String docRef;
    
    @Column(name = "CURRENCY_CODE", length = 20)
    private String currencyCode;
    
    @Column(name = "CURRENCY_RATE")
    private BigDecimal currencyRate;
    
    @Column(name = "PETTY_CASH_GL_POID")
    private Long pettyCashGlPoid;
    
    @Column(name = "PAYING_TO", length = 500)
    private String payingTo;
    
    @Column(name = "IOU_AMOUNT")
    private BigDecimal iouAmount;
    
    @Column(name = "SETTLED_AMOUNT")
    private BigDecimal settledAmount;
    
    @Column(name = "BALANCE_AMOUNT")
    private BigDecimal balanceAmount;
    
    @Column(name = "NARRATION", length = 1000)
    private String narration;
    
    @Column(name = "STATUS", length = 100)
    private String status;
    
    @Column(name = "CLOSED_REASON", length = 1000)
    private String closedReason;
    
    @Column(name = "REMARKS", length = 1000)
    private String remarks;
    
    @Column(name = "DELETED", length = 1)
    private String deleted = "N";
    
    @Column(name = "CREATED_BY", length = 20)
    private String createdBy;
    
    @Column(name = "CREATED_DATE")
    private LocalDateTime createdDate;
    
    @Column(name = "LASTMODIFIED_BY", length = 20)
    private String lastModifiedBy;
    
    @Column(name = "LASTMODIFIED_DATE")
    private LocalDateTime lastModifiedDate;
}