package com.asg.finance.dto;

import com.asg.common.lib.dto.CompanyDto;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Getter
@Setter
public class HrEmployeeDto {
    private Long employeePoid;
    private Long groupPoid;
    private String employeeCode;
    private String employeeName;
    private String employeeName2;
    private String baseGroup;
    private CompanyDto companyPoid;
    private Long locationPoid;
    private Long departmentPoid;
    private Long designationPoid;
    private String gender;
    private String maritalStatus;
    private LocalDate joinDate;
    private LocalDate dateOfBirth;
    private String presentAddress;
    private String permanentAddress;
    private String postalAddress;
    private String homeCountryPhone;
    private String mobile;
    private String personalEmail;
    private String businessEmail;
    private String bloodGroup;
    private String emergencyContactPerson;
    private String emergencyContactNo;
    private LocalDate serviceStartDate;
    private String serviceType;
    private LocalDate contractStart;
    private LocalDate contractEnd;
    private String probation;
    private String noticePeriod;
    private Long directSupervisorPoid;
    private Long loginUserPoid;
    private String jobDescription;
    private Long airSectorPoid;
    private String ticketPeriod;
    private String noOfTickets;
    private String accessCardIssued;
    private String discontinued;
    private LocalDate discontinuedDate;
    private String reason;
    private BigDecimal basicSalary;
    private BigDecimal netSalary;
    private Long currencyPoid;
    private String paymentMethod;
    private Long bankPoid;
    private String accountNo;
    private String iban;
    private BigDecimal registeredSalary;
    private LocalDate lastIncrementDate;
    private LocalDate nextIncrementDate;
    private BigDecimal holdSalary;
    private String holdReason;
    private String passportNo;
    private LocalDate passportIssuedDate;
    private LocalDate passportExpiryDate;
    private String placeOfIssue;
    private String passportPossessedBy;
    private String gosiNo;
    private BigDecimal gosiReturnAmount;
    private String cprNo;
    private LocalDate cprExpiryDate;
    private String cprOccupation;
    private String medicalInsurance;
    private LocalDate medicalInsuranceExpiryDate;
    private String rpNo;
    private LocalDate rpStartDate;
    private LocalDate rpExpiryDate;
    private String active;
    private String createdBy;
    private LocalDateTime createdDate;
    private String lastModifiedBy;
    private LocalDateTime lastModifiedDate;
    private String employeeBiomatrixId;
    private String otApplicable;
    private String insuranceNominee;
    private String insuranceNomineeRelation;
    private Long shiftPoid;
    private String currencyCode;
    private String deleted;
    private LocalDate drivingLicExp;
    private String nomineeContactDtl;
    private String displayName;
}
